"""Initial schema

Revision ID: 98e0da0f0c11
Revises: 
Create Date: 2026-03-09 14:58:39.328889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e0da0f0c11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_meta',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('price_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pricecharting_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('loose_usd', sa.Float(), nullable=True),
    sa.Column('cib_usd', sa.Float(), nullable=True),
    sa.Column('new_usd', sa.Float(), nullable=True),
    sa.Column('loose_eur', sa.Float(), nullable=True),
    sa.Column('cib_eur', sa.Float(), nullable=True),
    sa.Column('new_eur', sa.Float(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('scraped_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('changed_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_catalog_platform', 'price_catalog', ['platform'], unique=False)
    op.create_index('idx_price_catalog_platform_pcid', 'price_catalog', ['platform', 'pricecharting_id'], unique=False)
    op.create_index('idx_price_catalog_platform_title', 'price_catalog', ['platform', 'title'], unique=False, sqlite_where=None)
    op.create_index('idx_price_catalog_title', 'price_catalog', ['title'], unique=False, sqlite_where=None)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), server_default='pricecharting', nullable=True),
    sa.Column('loose_price', sa.Float(), nullable=True),
    sa.Column('complete_price', sa.Float(), nullable=True),
    sa.Column('new_price', sa.Float(), nullable=True),
    sa.Column('eur_rate', sa.Float(), nullable=True),
    sa.Column('pricecharting_id', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.String(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('item_type', sa.String(), server_default='game', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'item_type')
    op.drop_table('price_history')
    op.drop_index('idx_price_catalog_title', table_name='price_catalog', sqlite_where=None)
    op.drop_index('idx_price_catalog_platform_title', table_name='price_catalog', sqlite_where=None)
    op.drop_index('idx_price_catalog_platform_pcid', table_name='price_catalog')
    op.drop_index('idx_price_catalog_platform', table_name='price_catalog')
    op.drop_table('price_catalog')
    op.drop_table('app_meta')
    # ### end Alembic commands ###
